name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'

    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w -s -X main.Version=${{ steps.version.outputs.VERSION }}" -o shadowfax-linux-amd64 ./cmd/shadowfax
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-w -s -X main.Version=${{ steps.version.outputs.VERSION }}" -o shadowfax-darwin-amd64 ./cmd/shadowfax
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-w -s -X main.Version=${{ steps.version.outputs.VERSION }}" -o shadowfax-darwin-arm64 ./cmd/shadowfax

    - name: Upload linux asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./shadowfax-linux-amd64
        asset_name: shadowfax-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS AMD64 asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./shadowfax-darwin-amd64
        asset_name: shadowfax-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS ARM64 asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./shadowfax-darwin-arm64
        asset_name: shadowfax-darwin-arm64
        asset_content_type: application/octet-stream
